### ISSUE TITLE
图标乱码

### ISSUE THREAD

**Issue by otto-apoc-ksp** [zjuyk/dotfiles#1]
大佬，这个配置mpv的图标乱码，这个是什么原因造成的啊
![image](https://github.com/user-attachments/assets/87402277-cf24-4c17-beb0-8b5467838a24)

**Comment by zjuyk** [comment]
因为你缺少了对应的字体，如果你是 Arch 用户，可以使用这个包 ttf-material-design-iconic-font，我放到了 CN 源
